// SPDX-License-Identifier: MIT OR Apache-2.0

//! Acceptance for the analog stim adapter (issue #52): the Rust front end for
//! the shipped `merged_v2` bank must agree with the Python reference encoder,
//! value for value, on a fixture both languages read.
//!
//! `tools/live_stim_parity.py` runs `tools/hamming_encode.py` — the encoder
//! whose output `tools/hamming_lif.py` steps as `v = decay * v + W @ stim` —
//! over `tools/fixtures/live_stim/reading.jsonl` and pins the result in
//! `expected_stim.json`. This file reads the same two artifacts and asserts
//! [`LiveStimAdapter`] reproduces the pin exactly, so for every input class the
//! fixtures cover, neither implementation can move without the other failing.
//! CI runs both halves.
//!
//! The JSONL carries what JSON literals can express. The pin's `bit_exact`
//! section carries what they cannot — `NaN`, the infinities, an `f64` past the
//! binary32 ceiling, negative zero, subnormals — as raw bit patterns, which is
//! the only way the refusal contract gets cross-language coverage at all. The
//! one known uncovered divergence, a degenerate span, is documented on
//! `spikenaut_snn::stim` and is unreachable on this bank.
//!
//! The parity claim is about the `stim` vector, which is the thing both sides
//! actually produce. It is deliberately *not* a claim that this crate
//! reproduces the reference stepper: `tools/hamming_lif.py` remains the only
//! place in this repository that steps the shipped weights through a membrane.
//! (`src/neuromod_host.rs` steps a LIF too, but a default published
//! `neuromod::LifNeuron` that never sees those weights.)

use nir_rs::NirNode;
use nir_rs::types::TensorData;
use spikenaut_snn::encode::{CHANNEL_COUNT, LIVE_COLUMNS, LIVE_LEGAL_COLUMNS};
use spikenaut_snn::graph::{self, LIF_NODE, LINEAR_NODE};
use spikenaut_snn::json::{self, Json};
use spikenaut_snn::kinetic::LIVE_RAW_RANGES;
use spikenaut_snn::model::{NEURON_COUNT, SnnModel, TIMESTEP_SECONDS};
use spikenaut_snn::stim::{LiveStimAdapter, NO_STIMULUS, UNUSED_AXONS};

/// The raw v3 `state_telemetry` rows both encoders read.
const READING_JSONL: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tools/fixtures/live_stim/reading.jsonl"
));

/// The `stim` vectors `tools/hamming_encode.py` produces for those rows.
const EXPECTED_STIM_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tools/fixtures/live_stim/expected_stim.json"
));

/// Path of the fixture as the pin names it.
///
/// `tools/live_stim_parity.py` always writes this exact string, so the guard
/// does not catch a pin regenerated by that tool against another file — it
/// cannot be. What it catches is a hand-edited pin, or one copied in from
/// somewhere else, being compared against this fixture as if it described it.
const READING_REL: &str = "tools/fixtures/live_stim/reading.jsonl";

/// One fixture row: the raw reading, and the vector the reference encoded.
struct ParityRow {
    line: usize,
    episode_id: String,
    reading: [Option<f64>; LIVE_LEGAL_COLUMNS],
    expected: [f64; CHANNEL_COUNT],
}

/// Parse the JSONL, one non-blank line per row, keeping the true file line.
fn raw_rows() -> Vec<(usize, Json)> {
    READING_JSONL
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .split('\n')
        .enumerate()
        .filter(|(_, line)| !line.trim().is_empty())
        .map(|(index, line)| {
            let parsed = json::parse(line)
                .unwrap_or_else(|err| panic!("{READING_REL}:{}: {err}", index + 1));
            // A bare scalar or array is valid JSON and would sail through:
            // `Json::get` returns `None` for every column on a non-object, so
            // `reading_of` would read it as five absent sensors and encode an
            // all-zero vector. A corrupt fixture would then quietly agree with
            // any pin whose rows are zero.
            assert!(
                parsed.as_object().is_some(),
                "{READING_REL}:{}: expected a JSON object, got {}",
                index + 1,
                parsed.type_name(),
            );
            (index + 1, parsed)
        })
        .collect()
}

/// One raw row as the adapter's reading: absent and `null` are both `None`.
///
/// The same rule as `hamming_encode._live_number`. A non-numeric value is a
/// corrupt fixture rather than a runtime condition, so it panics here instead
/// of becoming an adapter error variant.
fn reading_of(row: &Json, line: usize) -> [Option<f64>; LIVE_LEGAL_COLUMNS] {
    LIVE_COLUMNS.map(|column| match row.get(column) {
        None | Some(Json::Null) => None,
        Some(Json::Number(value)) => Some(*value),
        Some(other) => panic!(
            "{READING_REL}:{line}: {column} must be a number or null, got {}",
            other.type_name()
        ),
    })
}

/// The pinned payload, checked for the metadata that makes it comparable.
fn parity_rows() -> Vec<ParityRow> {
    let pin = json::parse(EXPECTED_STIM_JSON).expect("expected_stim.json parses");

    assert_eq!(
        pin.get("fixture").and_then(Json::as_str),
        Some(READING_REL),
        "the pin must name the fixture this test reads",
    );
    assert_eq!(
        pin.get("unused_axons").and_then(Json::as_str),
        Some("5:15"),
        "the pin must carry the bank's unused-axon contract",
    );
    // The reference and the adapter each claim to normalise against the spans
    // the sidecar froze. Rust is held to that by
    // `shipped_bank_frozen_minmax_matches_live_raw_ranges` and Python by
    // `live_stim_parity.frozen_minmax_failures`; this is the third edge of the
    // triangle, so the two cannot agree on a span the bank never froze.
    let spans = pin
        .get("frozen_minmax")
        .expect("the pin carries the spans it normalised against");
    for (axon, sensor) in LIVE_COLUMNS.into_iter().enumerate() {
        let span = spans
            .get(sensor)
            .and_then(Json::as_array)
            .unwrap_or_else(|| panic!("the pin has a span for {sensor}"));
        let recorded = (
            span[0].as_f64().expect("min"),
            span[1].as_f64().expect("max"),
        );
        assert_eq!(
            recorded, LIVE_RAW_RANGES[axon],
            "axon {axon} ({sensor}): the pin and the crate disagree on the frozen span",
        );
    }

    let columns = pin
        .get("live_columns")
        .and_then(Json::as_array)
        .expect("the pin lists its live columns");
    assert_eq!(columns.len(), LIVE_LEGAL_COLUMNS);
    for (axon, column) in columns.iter().enumerate() {
        assert_eq!(
            column.as_str(),
            Some(LIVE_COLUMNS[axon]),
            "axon {axon}: the pin and the crate must agree on the column order",
        );
    }

    let samples = pin
        .get("samples")
        .and_then(Json::as_array)
        .expect("the pin carries its samples");
    let raw = raw_rows();
    assert!(!samples.is_empty(), "an empty pin would pass vacuously");
    assert_eq!(
        samples.len(),
        raw.len(),
        "every fixture row must be pinned; a dropped row is a silent hole",
    );

    samples
        .iter()
        .zip(raw)
        .map(|(sample, (line, row))| {
            let pinned_line = sample
                .get("line")
                .and_then(Json::as_f64)
                .expect("each sample names its source line") as usize;
            assert_eq!(
                pinned_line, line,
                "the pin and the fixture must be in the same order",
            );
            let stim = sample
                .get("stim")
                .and_then(Json::as_array)
                .expect("each sample carries a stim vector");
            assert_eq!(
                stim.len(),
                CHANNEL_COUNT,
                "line {line}: stim is the 16-wide vector `W @ stim` consumes",
            );
            ParityRow {
                line,
                episode_id: sample
                    .get("episode_id")
                    .and_then(Json::as_str)
                    .unwrap_or_default()
                    .to_owned(),
                reading: reading_of(&row, line),
                expected: std::array::from_fn(|axon| {
                    stim[axon].as_f64().expect("each axon is a number")
                }),
            }
        })
        .collect()
}

/// The label for an axon in an assertion message.
fn axon_label(axon: usize) -> &'static str {
    if axon < LIVE_LEGAL_COLUMNS {
        LIVE_COLUMNS[axon]
    } else {
        "unused"
    }
}

/// Acceptance: the Rust adapter and the Python reference encoder produce the
/// same `stim` vector for the same raw reading.
///
/// Exact equality, not a tolerance. Both sides are binary32 values that widen
/// into `f64` without loss, so the only thing a tolerance could absorb is a
/// real divergence — and the sharpest one available is exactly one ulp: the
/// reference snaps each raw sample onto the binary32 grid before normalising,
/// and the last fixture row is chosen so that skipping that snap moves every
/// live axon.
#[test]
fn the_adapter_reproduces_the_python_reference_stim() {
    let adapter = LiveStimAdapter::for_shipped_merged_v2()
        .expect("the analog pairing is the one that constructs");

    let rows = parity_rows();
    for row in &rows {
        let stim = adapter
            .stim_optional(row.reading)
            .unwrap_or_else(|err| panic!("{READING_REL}:{}: {err}", row.line));

        for (axon, &expected) in row.expected.iter().enumerate() {
            assert_eq!(
                f64::from(stim[axon]),
                expected,
                "{READING_REL}:{} ({}) axon {axon} ({}): the Rust adapter and \
                 tools/hamming_encode.py disagree",
                row.line,
                row.episode_id,
                axon_label(axon),
            );
        }
    }

    // The fixture has to be worth reading: if every pinned vector were zero,
    // the comparison above would hold for an adapter that returned zeros.
    assert!(
        rows.iter()
            .flat_map(|row| row.expected[..LIVE_LEGAL_COLUMNS].iter())
            .any(|&value| value != 0.0 && value != 1.0),
        "the fixture must exercise values between the span endpoints",
    );
}

/// One reading JSON literals cannot carry, and what the reference did with it.
struct BitExactCase {
    label: String,
    reading: [f64; LIVE_LEGAL_COLUMNS],
    /// `None` when the reference refused the reading.
    expected: Option<[f32; CHANNEL_COUNT]>,
}

/// Parse a big-endian IEEE-754 hex bit pattern, MSB first.
///
/// The readings travel as bits rather than as decimals because that is the
/// only way some of them travel at all: JSON has no `NaN`, no infinities, and
/// no way to distinguish `-0.0` from `0.0` once a parser has been near it.
fn bits_f64(hex: &str, what: &str) -> f64 {
    f64::from_bits(
        u64::from_str_radix(hex, 16).unwrap_or_else(|err| panic!("{what}: {hex:?}: {err}")),
    )
}

fn bits_f32(hex: &str, what: &str) -> f32 {
    f32::from_bits(
        u32::from_str_radix(hex, 16).unwrap_or_else(|err| panic!("{what}: {hex:?}: {err}")),
    )
}

/// The `bit_exact` section of the pin.
fn bit_exact_cases() -> Vec<BitExactCase> {
    let pin = json::parse(EXPECTED_STIM_JSON).expect("expected_stim.json parses");
    let cases = pin
        .get("bit_exact")
        .and_then(Json::as_array)
        .expect("the pin carries its bit-exact cases");
    assert!(!cases.is_empty(), "an empty section would pass vacuously");

    cases
        .iter()
        .map(|case| {
            let label = case
                .get("label")
                .and_then(Json::as_str)
                .expect("each case is labelled")
                .to_owned();
            let reading_bits = case
                .get("reading_bits")
                .and_then(Json::as_array)
                .expect("each case carries its reading");
            assert_eq!(reading_bits.len(), LIVE_LEGAL_COLUMNS, "{label}");
            let reading = std::array::from_fn(|axon| {
                bits_f64(
                    reading_bits[axon]
                        .as_str()
                        .expect("reading bits are strings"),
                    &label,
                )
            });
            let refused = case
                .get("refused")
                .and_then(Json::as_bool)
                .expect("each case records whether the reference refused it");
            let expected = (!refused).then(|| {
                let stim_bits = case
                    .get("stim_bits")
                    .and_then(Json::as_array)
                    .expect("an accepted case carries its vector");
                assert_eq!(stim_bits.len(), CHANNEL_COUNT, "{label}");
                std::array::from_fn(|axon| {
                    bits_f32(
                        stim_bits[axon].as_str().expect("stim bits are strings"),
                        &label,
                    )
                })
            });
            BitExactCase {
                label,
                reading,
                expected,
            }
        })
        .collect()
}

/// Acceptance, second half: the two encoders agree on the readings the JSONL
/// fixture structurally cannot hold.
///
/// `NaN`, the infinities and an `f64` past the binary32 ceiling have no JSON
/// literal, and a row carrying one would make the pin generator refuse the
/// whole file rather than record an expectation. So the entire refusal
/// contract — the thing `NonFiniteLiveFrame` exists for — had no cross-language
/// coverage until these cases carried it as raw bits.
///
/// `-0.0` is here for a quieter reason. Both sides return a *positive* zero for
/// it, but by different arithmetic: Python's `max(0.0, -0.0)` returns `+0.0`,
/// while Rust's `f64::clamp` preserves `-0.0` and only loses the sign in the
/// trailing `lo + (hi - lo) * unit` of `normalize_live`. Agreement that rests
/// on a term that looks removable is worth pinning, so this compares bit
/// patterns rather than values — `-0.0 == 0.0` would pass either way.
#[test]
fn the_adapter_agrees_on_readings_json_cannot_carry() {
    let adapter = LiveStimAdapter::new();
    let cases = bit_exact_cases();
    let (mut refused, mut accepted) = (0_usize, 0_usize);

    for case in &cases {
        match (&case.expected, adapter.stim(case.reading)) {
            (None, Ok(stim)) => panic!(
                "bit_exact[{}]: the reference refused {:?}, the adapter returned {stim:?}",
                case.label, case.reading,
            ),
            (Some(_), Err(err)) => panic!(
                "bit_exact[{}]: the reference accepted {:?}, the adapter said {err}",
                case.label, case.reading,
            ),
            (None, Err(_)) => refused += 1,
            (Some(expected), Ok(stim)) => {
                for (axon, (&want, &got)) in expected.iter().zip(stim.iter()).enumerate() {
                    assert_eq!(
                        got.to_bits(),
                        want.to_bits(),
                        "bit_exact[{}] axon {axon} ({}): adapter {got} (0x{:08x}) vs \
                         reference {want} (0x{:08x})",
                        case.label,
                        axon_label(axon),
                        got.to_bits(),
                        want.to_bits(),
                    );
                }
                accepted += 1;
            }
        }
    }

    // Both halves have to be populated, or this test silently becomes a test
    // of only one of them.
    assert!(refused > 0, "no case exercised the refusal path");
    assert!(accepted > 0, "no case exercised the accepted path");
}

/// The frozen span endpoints are exactly representable in binary32.
///
/// The reference divides by `f32(hi) - f32(lo)`; the adapter divides by the
/// raw `f64` difference. Those are the same number only while every endpoint
/// survives a binary32 round trip unchanged. All ten shipped endpoints do —
/// but that is a property of the numbers the sidecar froze, not of either
/// implementation, so nothing enforces it except this.
#[test]
fn the_frozen_span_endpoints_are_exactly_binary32() {
    for (axon, &(min, max)) in LIVE_RAW_RANGES.iter().enumerate() {
        for (name, value) in [("min", min), ("max", max)] {
            assert_eq!(
                f64::from(value as f32),
                value,
                "axon {axon} ({}) {name} = {value} is not exactly binary32; the \
                 reference would divide by a different span than the adapter",
                LIVE_COLUMNS[axon],
            );
        }
    }
}

/// The `unused_axons: "5:15"` contract, checked the way
/// `hamming_core.py::_unused_axon_notes` checks it: exactly zero, never
/// merely small.
///
/// On the Rust side this cannot fail by construction — `stim_optional`
/// initialises the vector to [`NO_STIMULUS`] and never writes an index past
/// the fifth — which is the design, not an oversight: the leak is
/// unrepresentable rather than detectable. What the test adds is the *pin*
/// side of the same contract, where it can fail: the reference's vectors,
/// carried in `expected_stim.json`, are held to the same rule. Keeping the
/// structural assertions alongside it means a refactor that started writing
/// past axon 4 fails here rather than somewhere downstream.
#[test]
fn no_fixture_row_leaks_onto_an_unused_axon() {
    let adapter = LiveStimAdapter::new();

    for row in parity_rows() {
        let stim = adapter
            .stim_optional(row.reading)
            .unwrap_or_else(|err| panic!("{READING_REL}:{}: {err}", row.line));

        for axon in UNUSED_AXONS {
            // The Python guard is `sample.stim[axon] != 0.0`; the bit
            // comparison is strictly stronger, because `-0.0` would slip
            // through a value comparison while being a different f32.
            assert_eq!(
                stim[axon], NO_STIMULUS,
                "{READING_REL}:{}: UNUSED-AXON LEAK on axon {axon}",
                row.line,
            );
            assert_eq!(
                stim[axon].to_bits(),
                NO_STIMULUS.to_bits(),
                "{READING_REL}:{}: axon {axon} must be a positive zero",
                row.line,
            );
            // The pin agrees, so the leak cannot be introduced on either side
            // alone.
            assert_eq!(row.expected[axon], 0.0, "line {}: axon {axon}", row.line);
        }
    }
}

/// Acceptance: the round trip into the graph. `Input → Linear` is the node
/// that consumes `stim`, and this is what consuming it looks like.
///
/// Two of the three assertions here are documentation rather than detection,
/// and it is worth being plain about which:
///
/// - `all_axons == current(LIVE_LEGAL_COLUMNS)` holds for *any* stim vector on
///   this bank, because both the unused axons and the weights on their columns
///   are structurally zero. It shows the shape of the round trip; it detects
///   nothing. See `the_graph_cannot_be_moved_by_an_unused_axon`.
/// - the one-step recurrence check is a property of the graph's `tau` and `r`,
///   already covered by `one_step_from_rest_reproduces_the_weighted_input` in
///   `tests/nir_graph.rs`. It is repeated here so this file reads as a
///   complete round trip.
/// - the current actually *responding* to the reading is the assertion with
///   content: an adapter that returned a constant vector would pass everything
///   above it and fail that one.
///
/// The claim is about the input term `I = W @ stim` and the one-step LIF
/// recurrence the graph reproduces. It is not a claim that this crate matches
/// the reference stepper's `f32` accumulation order — the reference sums in
/// binary32, and this crate does not step these weights at all.
#[test]
fn the_stim_vector_rides_the_linear_node_into_the_graph() {
    let adapter = LiveStimAdapter::new();
    let model = SnnModel::load_default().expect("the shipped model loads");
    let graph = graph::build_lif_graph(&model).expect("the shipped model builds a graph");

    let Some(NirNode::Linear(linear)) = graph.get(LINEAR_NODE) else {
        panic!("the learned weights ride the Linear node");
    };
    let TensorData::F64(weight) = linear.weight.data() else {
        panic!("expected an f64 weight tensor");
    };
    let Some(NirNode::Lif(lif)) = graph.get(LIF_NODE) else {
        panic!("expected a LIF node");
    };
    let (TensorData::F64(taus), TensorData::F64(rs)) = (lif.tau.data(), lif.r.data()) else {
        panic!("expected f64 tau and r tensors");
    };

    // Keyed by fixture line, so the responsiveness check below compares two
    // readings that genuinely differ rather than two copies of one.
    let mut currents: Vec<(usize, Vec<f64>)> = Vec::new();

    for row in parity_rows() {
        let stim = adapter
            .stim_optional(row.reading)
            .unwrap_or_else(|err| panic!("{READING_REL}:{}: {err}", row.line));
        let mut row_currents = Vec::with_capacity(NEURON_COUNT);

        for unit in 0..NEURON_COUNT {
            let current = |axons: usize| -> f64 {
                (0..axons)
                    .map(|axon| weight[unit * CHANNEL_COUNT + axon] * f64::from(stim[axon]))
                    .sum()
            };

            // `Linear` computes `I = W @ stim` across all 16 axons, and the
            // five live ones account for every bit of it.
            //
            // This equality does *not* detect an unused-axon leak, and must
            // not be read as if it did -- see
            // `the_graph_cannot_be_moved_by_an_unused_axon` for why it cannot,
            // and `no_fixture_row_leaks_onto_an_unused_axon` for the check
            // that does. What it documents is the round trip itself: the
            // vector the adapter builds is the vector this node consumes.
            let all_axons = current(CHANNEL_COUNT);
            assert_eq!(
                all_axons,
                current(LIVE_LEGAL_COLUMNS),
                "{READING_REL}:{} unit {unit}: axons 5-15 moved the current",
                row.line,
            );

            // One NIR step from rest is the reference recurrence with `v = 0`:
            // `v = decay * 0 + W @ stim`.
            let decay = (-TIMESTEP_SECONDS / taus[unit]).exp();
            let stepped = rs[unit] * (1.0 - decay) * all_axons;
            assert!(
                (stepped - all_axons).abs() <= 1e-12 * all_axons.abs().max(1.0),
                "{READING_REL}:{} unit {unit}: one step gave {stepped}, \
                 `v = decay * v + W @ stim` from rest gives {all_axons}",
                row.line,
            );
            row_currents.push(all_axons);
        }
        currents.push((row.line, row_currents));
    }

    // The assertion with content: the current the graph computes has to depend
    // on the reading. Everything above holds for an adapter that returned the
    // same vector every time -- fixture line 1 is all zeros, so for that row it
    // holds for one that returned nothing at all.
    let saturated = currents
        .iter()
        .find(|(line, _)| *line == 2)
        .expect("fixture line 2 saturates every live axon");
    let idle = currents
        .iter()
        .find(|(line, _)| *line == 1)
        .expect("fixture line 1 sits every live axon at its span minimum");
    assert!(
        idle.1.iter().all(|current| *current == 0.0),
        "an all-zero stim must drive no current at all",
    );
    assert!(
        saturated.1.iter().any(|current| *current != 0.0),
        "a saturated reading must move `W @ stim`; the adapter is not responding \
         to its input",
    );
}

/// The second, independent reason axons 5-15 are inert on this bank: the
/// weights that would consume them are themselves exactly zero.
///
/// `snn_model.json` carries training residue on those columns — none of the 176
/// is exactly zero, and the largest is about `8e-15` against a Q8.8 grid step
/// of `1/256` — so the decode snaps every one of them to the nearest code,
/// which is `0`. The `Linear` node is therefore provably
/// insensitive to whatever arrives on axons 5-15, independently of the adapter
/// writing zeros there.
///
/// That is worth pinning rather than assuming, and it is also the reason
/// `the_stim_vector_rides_the_linear_node_into_the_graph` cannot double as a
/// leak detector: with a zero weight, any stim value multiplies to zero. A
/// future bank that learned on those columns would fail here, which is exactly
/// when the leak check stops being belt-and-braces.
#[test]
fn the_graph_cannot_be_moved_by_an_unused_axon() {
    let model = SnnModel::load_default().expect("the shipped model loads");
    let graph = graph::build_lif_graph(&model).expect("the shipped model builds a graph");
    let Some(NirNode::Linear(linear)) = graph.get(LINEAR_NODE) else {
        panic!("the learned weights ride the Linear node");
    };
    let TensorData::F64(weight) = linear.weight.data() else {
        panic!("expected an f64 weight tensor");
    };

    for unit in 0..NEURON_COUNT {
        for axon in UNUSED_AXONS {
            assert_eq!(
                weight[unit * CHANNEL_COUNT + axon],
                0.0,
                "unit {unit} axon {axon}: the graph carries a non-zero weight on \
                 an unused column, so the leak check is no longer belt-and-braces",
            );
        }
        // Not vacuous: the live columns are not all zero, so this is a claim
        // about the unused width rather than about an empty matrix.
        assert!(
            (0..LIVE_LEGAL_COLUMNS).any(|axon| weight[unit * CHANNEL_COUNT + axon] != 0.0),
            "unit {unit}: the live columns must carry learned weights",
        );
    }
}

/// A reading the bank cannot represent is refused rather than saturated, and
/// refusal names the sensor.
///
/// The reference refuses the same values, though not all from one place:
/// `hamming_encode._live_number` rejects `NaN` and the infinities before
/// `frozen_unit01` is reached, and `hamming_const.f32` rejects what binary32
/// cannot hold. `the_adapter_agrees_on_readings_json_cannot_carry` is what
/// pins that agreement; this test pins the Rust side's own naming.
#[test]
fn an_unrepresentable_reading_is_refused_by_name() {
    let adapter = LiveStimAdapter::new();
    let good = [42.0, 180.0, 61.0, 1_900.0, 9_500.0];
    assert!(adapter.stim(good).is_ok());

    for (axon, sensor) in LIVE_COLUMNS.into_iter().enumerate() {
        for bad in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY, 1e300] {
            let mut reading = good;
            reading[axon] = bad;
            let rejected = adapter
                .stim(reading)
                .expect_err("a reading outside binary32 is not a stimulus");
            assert_eq!(rejected.sensors().collect::<Vec<_>>(), [sensor]);
            assert_eq!(rejected.first_channel(), axon);
        }
    }

    // The adapter is stateless, so a refusal costs nothing: there is no
    // accumulator to leave half-advanced, and the next reading encodes
    // normally.
    assert!(adapter.stim(good).is_ok());
}
